FROM wordpress

ENV APT_DEPS \
        libldap2-dev

# Install PHP LDAP extension
RUN apt-get update && apt-get install -y ${APT_DEPS} \
        && docker-php-ext-configure ldap --with-libdir=lib/x86_64-linux-gnu/ \
        && docker-php-ext-install ldap


